[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "9aa33e1c429f1180192c5bd02c9699b839d3183b"
os = "macos"

    [[Notcurses.download]]
    sha256 = "0e9a2337942ee2811742d60eee6de2794402c8ba260ba2bd1807ad335a07e2e1"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.aarch64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "c7322c8becaaf7e7dda89812c54ff692bc18f472"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "6e5c70d674ac4b6957e08a92dd111bbf45c78fd236ee0adfc664219005e8295a"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.aarch64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "5c533c16d354e70a4df044907dfe2b874994305f"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "03f2746f2295ef6a040cdc97c9d42a1c25177181ce1dd2d0b0c4a3f193e8adc0"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.aarch64-linux-musl.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fd3d2d6edb1a28a40ea02bd910b4df990e10b34f"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "ae5442fe9371ca29f3163815a45cec5fdf166eb3dcf0ed85834b0bd55fa240d3"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.armv6l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5626f530f24b244b623dadd8023ce63228bb960a"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "01efca086562931bc81d8dd57301617a93bc4d347a1d9ead1120a1f66e2c2298"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.armv6l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8653fb340c8d5651661f93990b44e41bb602cfc"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "2329e58953258dd5bef73effea92c84af3bd199bf5e6540e949fdab01bff7ec7"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.armv7l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67211cf4fcb2ab56940d06f9bc2927354e87113b"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "561e5f69dcbf2d4199ffc5b36d06f389bc10f022fd18a174ade36d61c5ff05c7"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.armv7l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "9235ccb277c85a3518604ee9be022860ba55235c"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "1af3779ae1e270d4202b4e9da1f8e8339098ea6006676a4cfd74384581b23d4b"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.i686-linux-gnu.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "a6a1ccb7375731b3697c01e6ffe2e83adae3acae"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "5382f0b0fb3136b26ae0c6082e8849d1ed0b144c2b4eebd11be2e1dac913f529"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.i686-linux-musl.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "66b0046d871fb4697af7a1893ef387b88e99443d"
os = "windows"

    [[Notcurses.download]]
    sha256 = "60d0a44ea4e53a6bd724f61d524d54f1c42d3b6d183c2bbbe23040aa904c06dd"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.i686-w64-mingw32.tar.gz"
[[Notcurses]]
arch = "powerpc64le"
git-tree-sha1 = "6747b8575730c17e0ec25fdc57f89be7db957ee3"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "f093f7cd802de19e155fa25debb3b1da1024b519e3406603fe42d096e97befa7"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.powerpc64le-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "4e6c34ada7c80428670811737b1fd7ae8c553b64"
os = "macos"

    [[Notcurses.download]]
    sha256 = "2d8778160e09f27e0f446ee3e5d40972716424cc78af5646cdef35d283e30984"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.x86_64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "68dca362dd740958e0cc7e5a0a4e5a333e7e09bc"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "f8885d6e6e57075c5a35d2c1f20787903d1523267063e7d50de02072d7a05ca1"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.x86_64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "0bacd8aa168c6d43bbc18959106aad75c077d8d5"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "8a0cb8628b58aa0bc400f78ebfacfc7596408e4fe116fa9a8aa1591dff371e30"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.x86_64-linux-musl.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "5a87cfde64e37384eab6e32df15e2c38ebc4992e"
os = "freebsd"

    [[Notcurses.download]]
    sha256 = "380786b42ac28b430da05227d45c31e5dc7e5bced8d9c4a82824d91986a66510"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.x86_64-unknown-freebsd.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "5973cb4fb0f66729f8e645b3d559901e4046a761"
os = "windows"

    [[Notcurses.download]]
    sha256 = "151e41d49555fd012db0690c93b9a84fb8ef12bf7441b2fe9c3c2be12a26e14f"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.12+0/Notcurses.v3.0.12.x86_64-w64-mingw32.tar.gz"
