[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "db3870e3f5f6ecad5bdb7dfe3d6566d343875663"
os = "macos"

    [[Notcurses.download]]
    sha256 = "86303e766783fb97bdb0ae52a9214d3cde93b12af91f00b0d426acadc876a413"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.aarch64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "3951eb671319aac6e56092ac0bac696ee5682fd0"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "3aa71e2cf1fd2f5ad2d44660a66bccae0793a09305fdb67c099bc35afbcff38a"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.aarch64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "7b4c043c54ed9a698af9adc1eb3bee1aba500b7f"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "eb96aa557beca56e6663f23852a168370066967ef56510d6204945690aac6036"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.aarch64-linux-musl.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4c458df132fad85bdabd72ab5c0b4dbfa3862428"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "d668193fe8f3b731c37adcbd98fe9ee0cc2f9242a19267d771dea802bd7a5b48"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.armv6l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "28e508714b3b5adb20d5b1856ca44f571ed4d007"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "4584ba9bfb9344c5f27b4404cdfbd5451fec9ece75bb426a320569b32da2d35f"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.armv6l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38af895d88fa3fc173e164f6f82fe8bd5a695601"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "0de46b1d790998cb166ae607bf7f021433985efc48d136b00c814ac88163e5c7"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.armv7l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c58289c3a67ae8cd42de5525503162a7babb3cce"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "3bd2636dbec6948fdaf11966706878fded6f74e290dafb5f2f6efb12b7a9f2e9"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.armv7l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "c2818597da23b2f7b0e54a25349df505bc40d222"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "415005f42150d9fd594e69a9a649a0c3f9fd3d577434b5dcba3fbe0db5db1d36"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.i686-linux-gnu.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "86eb4fd0cfa5f9f649688685b59a991ae645bb87"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "d098ed29de49fb74d247a1d0f2e88713efc6ed52f22d7d4b40256e77f5f48bb1"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.i686-linux-musl.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "ae377edc348d653a74e38e77e04b752f40195be9"
os = "windows"

    [[Notcurses.download]]
    sha256 = "9c947589411f6c741b6334fd6892616dd16ee5870f52dc5248eee96ad7224bca"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.i686-w64-mingw32.tar.gz"
[[Notcurses]]
arch = "powerpc64le"
git-tree-sha1 = "320a453c8ee65222b6cbb472b92c0d9bf9726d13"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "5b38406f2065d7fff9df6e545940802ae6c97dfed1bbc5bb375e83ba27e447cd"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.powerpc64le-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "8a0729f3698fffd433a6b042f926fff66190ffad"
os = "macos"

    [[Notcurses.download]]
    sha256 = "cff74cb1beb4e24a6ce04a9322dbdb0c72f5f642276aa4ba9988518c5bda256f"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.x86_64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "d8696de28936673580271a2559e043782782bba8"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "dd785dc64151a44182cce0ebcaf6fd810d42612b253b3729a2b9c1de4717610f"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.x86_64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "5970a0c41d5373389afce573e80881f64c68d035"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "aee6cb564c2a59461a179fdd1e52e5f1680a6baf496a5d608bda02a90ec5a748"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.x86_64-linux-musl.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "7a6612b163086a7d93ad616a839974c38e283a45"
os = "freebsd"

    [[Notcurses.download]]
    sha256 = "54a8af3adc419480edc47b43eb625cb5ed2dd676690ec3c17700c3b8bdbf4b0f"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.x86_64-unknown-freebsd.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "e127a76df0e96638d79aa714c765a9d576e183b5"
os = "windows"

    [[Notcurses.download]]
    sha256 = "2f6e80c4a51a023b9e69521074f3b7c39b7cf4f3dc251496cbcf7bab55e4b9e6"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.13+0/Notcurses.v3.0.13.x86_64-w64-mingw32.tar.gz"
