[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "7d5f126390453e8e1626de488018946aa0bc696c"
os = "macos"

    [[Notcurses.download]]
    sha256 = "14ecfb5227956cbbd8cd80fcada25966d3e5a82549105218842e0d95fda63d9b"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.aarch64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "bf6171469b4c808afb2c4f3ea8ce92acf364e812"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "0f3cd235e1cfa816948b358a16743ed5778336f743a2feef16a80cdc194ff09c"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.aarch64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "d3236ff74dce47cdbe12c208764c86f41199a97e"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "e9969b69aa3687bbbf4a9a9123f943a62054d612596f8c6cb1f60c40e796c510"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.aarch64-linux-musl.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3310289a260d6d3c6fecbdd80a511ba54e0e6045"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "3cd22b14c2aa519f28ba3c920a6da5a7f6e74c76da165d0e2013f41995abacdd"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.armv6l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b98ff8dfbaa4c30114b7fd470695fc91e4da8333"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "cf6a8c15e71ee112b696b22f643a17db3d68eb4487ee3a25eebe772e75e0cdf1"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.armv6l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8ecd8f6d1000cf97cd4ab0d6956f431093a41fe"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "b55d5c07146169d84755e96c1350be80f4b8f2e2a13e326cce28d186a40a9fa3"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.armv7l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a2a11bb7bf0f087dcd028abf6bb187082bb1efaf"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "651073e82579dfd1184d546930e7a745d0dd7fd1d51ef9fde5ac6f85cf0748b8"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.armv7l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "4090983858335a127378d86d21f05d18df4d9061"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "5b2ee330a308404e0aa4ca7a4693f39df443fab2ce10d83d5bd7a43440052240"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.i686-linux-gnu.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "990d954de3c0e5e7bf1e56fb1f35638ac5e34d2c"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "5485fab343ad2f8fdc13a264a15a15d49333a33af537e60c8a5144c659aa0408"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.i686-linux-musl.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "d2dfa618b2b2f73f1bdb5991aa38ca9e15e236c5"
os = "windows"

    [[Notcurses.download]]
    sha256 = "e6b69f83cc3c8c8666dcde3dcba33a66138dc29ee866737986a8b66eeaa4eb7b"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.i686-w64-mingw32.tar.gz"
[[Notcurses]]
arch = "powerpc64le"
git-tree-sha1 = "2da8fc478bca768dffa12d54f894eab101f551ea"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "c3d9d0e4266bdc1caf90822fee1e7fbd6c3095dd3580ce754c50c7d5be6ed5df"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.powerpc64le-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "17e03b16b5232a397d3c1b54db3d7bb0b867b8b1"
os = "macos"

    [[Notcurses.download]]
    sha256 = "6d29f665f54ce427ef55e3bd21ae396aebb4425616c8165472751e8c86dd7084"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.x86_64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "77c7ab4d767e0348ddb6bf959bd74ec1fbf7a33b"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "a0cebf524d8240d4088e740fa6edcb195acc2751da01614748c0af2ff83f74cb"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.x86_64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "63f56f131abaf34492cf64453e96970c03424ac3"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "bddf0b134381889a0b482b8d265405d6f9dc6975a666d6f22d3f5a0376586a57"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.x86_64-linux-musl.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "aa8ec6a8dad0376c54fd93000380ac357262289a"
os = "freebsd"

    [[Notcurses.download]]
    sha256 = "151143461ae6c6501bf66c76b5e9310c4b9d06d002f5bfcd67a362f2939ebf06"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.x86_64-unknown-freebsd.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "34543734faa0e870860109c6b36b86b6ec83ef66"
os = "windows"

    [[Notcurses.download]]
    sha256 = "eaf1c8a1548af02ec6bea78d4c23f49272c6d39aab62d34beb23237b1c0076c5"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+0/Notcurses.v3.0.2.x86_64-w64-mingw32.tar.gz"
