[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "6efc40642615a08c0d78b1ac86930d52270a4363"
os = "macos"

    [[Notcurses.download]]
    sha256 = "994b265b5b85e138266cdca14574adbce58f8c82f85bae3c7ce74674bbe65c37"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.aarch64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "68cdb26054b3cd574de900be63a941226e643b07"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "7a88d6f47c59b68d7eb0bec595921ddfd92e047763a849ec4013354d99df8a12"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.aarch64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "ccaeb26658bc9a6d961c9c18e789edbf7f38ce5d"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "16b0df2a464c8207ffae4cb07569beaeaf20412bd45fb85e6de6e8075243045f"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.aarch64-linux-musl.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "02a63f3a1ed526ab38b3cdcd2f4bf5e2faa1c5ef"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "92190d871384afeb756071dcf9b68150328126f9d68a4e9b5654db6055a2e3a4"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.armv6l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d51b6f12e1321229396399c2904a87b0c61ffccb"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "18ead0122ab89338112f8252505b49da5dae215e540fcb3254401fa26f66f34a"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.armv6l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c817fdad7ba52a5918e08582814a40997dddb9ce"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "e655d50a19a293dab94b67c246ce0452a620940a3f918849c610f8be1197c7fd"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.armv7l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "124505667ac5cab9b83bd423aa7bc4fdc0776747"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "4d44cf89688332d39e242ffc3a04c8385a17d0b63dfe6d625ea0712d77394ae9"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.armv7l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "bec652997e2c37a49632126f1e5b75e2e31b76f5"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "dbca41f1d997194d5eed3672c489cb243705e100eaa7bcf2c3ee47890bd64954"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.i686-linux-gnu.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "761d13bb98b9da3588edab29b096ed923c07efec"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "2905bcf57a5aa2631bfe7b9e38eea3752538ebb0234b59e395ec3f4d90265a30"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.i686-linux-musl.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "9ca15984c465980f76c1811ff2734613440a0e59"
os = "windows"

    [[Notcurses.download]]
    sha256 = "73e0c4a39a703254fcc93461f1104f6b3b236f063b9ebbe24b6149cab8eafeab"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.i686-w64-mingw32.tar.gz"
[[Notcurses]]
arch = "powerpc64le"
git-tree-sha1 = "eb7e016a5956faee7dfb62afc6527290587a137b"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "8d7c14bc717b9618ce3224368d9c066744bb30e092f6ecc09cf157b63fccbf1c"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.powerpc64le-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "ea73e53bc3cce8faeff2322e1fafa9fddc4a5b37"
os = "macos"

    [[Notcurses.download]]
    sha256 = "abc48c69f0d97a3f323996b9ac2c9e6a9f2e06f14c69d56f185eacb27c09854d"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.x86_64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "85dd1f3b7f875445e27c492033ed06800dffe234"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "f7d9a9ee132d5093648b2599548a2e28f8f3520926ac336edea1825c2f2e5a4c"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.x86_64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "1dd6fa3aa8e24beeb068f601cff770a808f7b4f9"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "4b26048ea67b295bc71948ac9dda67c9cb4c5adb33a88e3f8060471f22a39321"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.x86_64-linux-musl.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "136f3b2dd94d0ee1478c0ed4acd74f2c01a9c30a"
os = "freebsd"

    [[Notcurses.download]]
    sha256 = "0a28d35d782e4edc2e82d677132bbb0e79b97f86d23a8723b989f8db66a23642"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.x86_64-unknown-freebsd.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "8e5b60cbfd2c8d5063856b0bafbc5fcaf59b48a6"
os = "windows"

    [[Notcurses.download]]
    sha256 = "6e73bc73a9fc63423b29f674c32ce5a8c4d3e0e093851f3981d3a4fc294cb906"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.11+0/Notcurses.v3.0.11.x86_64-w64-mingw32.tar.gz"
