[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "e84aaad7266e660cdb96e350b7c5c7a84f2d18fd"
os = "macos"

    [[Notcurses.download]]
    sha256 = "6a575b4750f8f7cceaca5b334b02032f66a46ffde1384d6ec7258eee89ea6cd3"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.aarch64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "81ea5301cd3393cfbbc7f4d81e5a1969503ab0db"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "343233e52be4eff82e5a506d695fd03552080c1c1f090890c8553049eb4bbdf1"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.aarch64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "aarch64"
git-tree-sha1 = "a63a346e770206cd6b710076a346a48f437c1dca"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "22dd365945c68d9731ecfe94cbef5e3d039c02f6cb3c43ea2ac5d4d8bd13ea8a"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.aarch64-linux-musl.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3c952e0867180328f9355d8d6efd2cb7fc247c19"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "f007ec58b202c00a8fea26545d7e0e4bc33b9ffa4a52c5724ae21ee0c3aa9183"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.armv6l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bfcd5fa726894c0a2ef57563a41fc3363f88a93e"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "a2878b110c957e505d3a3a4b4bef67f8a744b4bf79654a4b347542bbb8e7b7b8"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.armv6l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78de97453f148e1d21d0e2286663233f3f653c44"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "326fec985942568ee6e9fedf4bf6e68fbe03af188b45db8aff4f960adc5bb2e8"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.armv7l-linux-gnueabihf.tar.gz"
[[Notcurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ac74af24115c718f1dd145ae8d6c1149270623f"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "081dbb8a27c7f35e9a614068d207146b4fc26fce98983a234c4215fcf1ecd144"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.armv7l-linux-musleabihf.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "bfd71687bdcaf504fd8ffd868557a7ddebbf6ac0"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "e8206cfcc4949083d158e95994879fde30082a1c82f6b1970c9eecc46e1b9bf6"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.i686-linux-gnu.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "02aa2684b6413643c49a231d605bf8fb94ce7aa7"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "69381c549fd3457b5fa4030a768e182977b2f349876e6a985df36f429294b1f2"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.i686-linux-musl.tar.gz"
[[Notcurses]]
arch = "i686"
git-tree-sha1 = "90446124af5b019d56491609d5db4a27089e527c"
os = "windows"

    [[Notcurses.download]]
    sha256 = "64f99aa96f94c0ec37e8971058dfe2ba5eb4f0b268806a1462168af5e4192303"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.i686-w64-mingw32.tar.gz"
[[Notcurses]]
arch = "powerpc64le"
git-tree-sha1 = "702c1038e7aa1778f4f9e304c3bf225f92bb5bab"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "bf86a58b7cffc41b10f43e3d2843e62d310f65aad9a986ee88a08030ef9566c0"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.powerpc64le-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "2f808fb1278b03071c415cc5a2d671f151dd460f"
os = "macos"

    [[Notcurses.download]]
    sha256 = "40969943f3265640a065658acae68a14df86cfbf646965449c4456a4c1440551"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.x86_64-apple-darwin.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "06acdaaea0ec0428b89227b74d48c3878f3ae161"
libc = "glibc"
os = "linux"

    [[Notcurses.download]]
    sha256 = "7e6b10d2465144d8b436f057781dc8c509bd4afc671b90212a7f919553708658"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.x86_64-linux-gnu.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "3195a65aee2f0af4c169a0e53eaf33fe0d92aea9"
libc = "musl"
os = "linux"

    [[Notcurses.download]]
    sha256 = "faad2e6a5d4ad954cd0e2f092c30999bdc61a0b3f92d5cbc9f00ba8363754398"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.x86_64-linux-musl.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "b8bfb2c16b675d9fbc37372352bfe0fdb084672f"
os = "freebsd"

    [[Notcurses.download]]
    sha256 = "7c9e1397bc8a1f87ef55ab15634400b35833c177d780f19aa93f939934536e8e"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.x86_64-unknown-freebsd.tar.gz"
[[Notcurses]]
arch = "x86_64"
git-tree-sha1 = "37c1b2a498bb116d55d23156ad73ab6261dace33"
os = "windows"

    [[Notcurses.download]]
    sha256 = "2f1fe00df5264b8929ceb03cea56f5a7814c21edf62982d4456b4f5a62892a9f"
    url = "https://github.com/JuliaBinaryWrappers/Notcurses_jll.jl/releases/download/Notcurses-v3.0.2+1/Notcurses.v3.0.2.x86_64-w64-mingw32.tar.gz"
