# Autogenerated wrapper script for Notcurses_jll for i686-w64-mingw32
export libnotcurses, libnotcurses_core

using Ncurses_jll
using libunistring_jll
using libdeflate_jll
JLLWrappers.@generate_wrapper_header("Notcurses")
JLLWrappers.@declare_library_product(libnotcurses, "libnotcurses.dll")
JLLWrappers.@declare_library_product(libnotcurses_core, "libnotcurses-core.dll")
function __init__()
    JLLWrappers.@generate_init_header(Ncurses_jll, libunistring_jll, libdeflate_jll)
    JLLWrappers.@init_library_product(
        libnotcurses,
        "bin\\libnotcurses.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnotcurses_core,
        "bin\\libnotcurses-core.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
