# Autogenerated wrapper script for Notcurses_jll for x86_64-apple-darwin
export libnotcurses, libnotcurses_core, libnotcurses_ffi

using Ncurses_jll
using libunistring_jll
using libdeflate_jll
JLLWrappers.@generate_wrapper_header("Notcurses")
JLLWrappers.@declare_library_product(libnotcurses, "@rpath/libnotcurses.3.dylib")
JLLWrappers.@declare_library_product(libnotcurses_core, "@rpath/libnotcurses-core.3.dylib")
JLLWrappers.@declare_library_product(libnotcurses_ffi, "@rpath/libnotcurses-ffi.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Ncurses_jll, libunistring_jll, libdeflate_jll)
    JLLWrappers.@init_library_product(
        libnotcurses,
        "lib/libnotcurses.3.0.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnotcurses_core,
        "lib/libnotcurses-core.3.0.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnotcurses_ffi,
        "lib/libnotcurses-ffi.3.0.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
